### ISSUE TITLE
Layout warning

### ISSUE THREAD

**Issue by dan-bowen** [dan-bowen/nuxt-blog-starter#2]
`npm run dev` is logging the following error.

```
 WARN  Using <NuxtLayout> inside app.vue will cause unwanted layout shifting in your application.Consider removing <NuxtLayout> from app.vue and using it in your pages.
```
`app.vue` matches the [Nuxt docs for the app file](https://v3.nuxtjs.org/guide/directory-structure/app/#usage-with-pages) so I'm not sure what to make of it.

**Comment by Demivan** [comment]
Hi. Found this issue as a first link in Google when googling this Nuxt warning. :)

This error comes from `@nuxt/content` when `injectPage` is enabled. Because you have own `[...slug].vue` implementation, you just need to disable `injectPage` option.


By the way you can use: `const { page: blogPost } = useContent()` instead of `queryContent` when you have document-driven mode enabled.

**Comment by dan-bowen** [comment]
@Demivan Thank you so much for kindly helping me! I am using this repo to learn Vue and sometimes it is hard to find the answers on your own. Hopefully documenting and solving issues along the way will help others too.

Thank you again. 🙏

**Comment by dan-bowen** [comment]
This solved in PR https://github.com/dan-bowen/nuxt-blog-starter/pull/9

It may be useful to track the following upstream issue which may change the way this was resolved.

https://github.com/nuxt/nuxt.js/issues/15240
